export default {
  colors: {
    banner: "#fff",
    bannerBackground: "#222c",
    bannerAccent: "#fff",
    bannerAccentBackground: "#3b5998 ",
    button: "#fff",
    buttonBackground: "#3b5998 ",
    buttonDisabledBackground: "#999",
    buttonBorder: "#3b5998",
    error: "#ff0033",
    form: "#333",
    formAccent: "#008080",
    formBackground: "#eee",
    icon: "#eee",
    iconBackground: "#008080",
    nav: "#333",
    navAccent: "#008080",
    navBackground: "#fff",
    primary: "#333",
    primaryAccent: "#008080",
    primaryAccentBackground: "#ddd",
    primaryBackground: "#eee",
  },
  styling: {
    boxShadow: "box-shadow: 2px 2px 10px #333;",
    formShadow: "box-shadow: 3px 3px 8px #333;",
    iconShadow: "box-shadow: 2px 2px 5px #333;",
  },
  media: {
    tablet: "@media only screen and (min-width: 1024px)",
    desktop: "@media only screen and (min-width: 1280px)",
    standard: "@media only screen and (min-width: 1920px)",
  },
};
